'Not found' middleware
jasny/router pull request #7
Opened 2016-10-13 07:25 UTC by Minstel

2016-10-13 08:13 UTC, jasny requested changes

2016-10-13 08:13 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +        if (!in_array($notFound, [404, '404'], true) && !is_callable($notFound)) {
You should be able to use any valid http status code (100 - 999) for `$notFound`.

2016-10-13 08:13 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +        if ($methodNotAllowed && !in_array($methodNotAllowed, [405, '405'], true) && !is_callable($methodNotAllowed)) {
You should be able to use any valid http status code (100 - 999) for `$methodNotAllowed`.
You need to do `isset($methodNotAllowed)`, so `0` and `false` will also cause an exception.

2016-10-13 08:13 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +        $glob = new Glob($this->routes);
You mustn't create `Glob` here, `$this->routes` should already be a `Routes` object.

2016-10-13 08:13 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +    public function __construct(array $routes, $notFound = 404, $methodNotAllowed = null)
`$routes` must be a `Routes` object, not an array.

2016-10-13 08:13 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +        }
No need to duplicate the code in 2 `if` blocks here:

```
if (!$this->routes->hasRoute($request)) {
   $status = $this->methodNotAllowed && $this->routes->hasRoute($request, false)
       ? $this->methodNotAllowed
       : $this->notFound;
   ...
}
```

2016-10-13 08:13 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +                    $this->simpleResponse($response, $this->methodNotAllowed, 'Method Not Allowed') :
Just always use 'Not Found' as body text, regardless of the response code.

2016-10-13 12:17 UTC, jasny requested changes
Code is good. Tests need some improvements.

2016-10-13 12:17 UTC, jasny commented on src/Router/Middleware/NotFound.php
> +     * @param array $routes
Fix `@param Routes $routes`

2016-10-13 12:17 UTC, jasny commented on tests/Router/Middleware/NotFoundTest.php
> +        $middleware = new NotFound(new Glob([]), $notFound, $notAllowed);
Don't use `Glob`, but use a mock of `Routes`.

2016-10-13 12:17 UTC, jasny commented on tests/Router/Middleware/NotFoundTest.php
> +    public function getRequests($uri, $method)
method isn't used

2016-10-13 12:17 UTC, jasny commented on tests/Router/Middleware/NotFoundTest.php
> +
Please create tests for the case where
* the route **is** found
* the route isn't found at all
* the route isn't found, but exists for another method

2016-10-13 18:26 UTC, Minstel commented on tests/Router/Middleware/NotFoundTest.php
> +    public function getRequests($uri, $method)
It is.

2016-10-15 20:44 UTC, jasny commented
@Minstel Did you push to the wrong branch? Other middelware classes have been added. Please create a branch per middleware.

2016-10-18 13:19 UTC, jasny approved these changes

2016-10-18 13:24 UTC, merged